name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  build-js:
   name: Build JS
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run production
      
  build-php:
   name: Build PHP
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --optimize-autoloader --no-dev --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Configure application
      run: |
        php artisan config:cache
        php artisan view:cache
        php artisan key:generate
        php artisan migrate:refresh --force
        php artisan db:seed --force
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

