name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  build-js:
   name: Build JS
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run production

  build-php:
   name: Build PHP
   runs-on: ubuntu-latest

   services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tracy_test
        ports:
          - 50315
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
   env:
     DB_PORT: 50315
   steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --optimize-autoloader --no-dev --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Configure application
      run: |
        php artisan config:cache
        php artisan view:cache
        php artisan key:generate
        php artisan migrate:fresh --seed --force
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

